import { unstable_getServerSession } from 'next-auth'
import { useSession } from 'next-auth/react'
import Head from 'next/head'
import { authOptions } from './api/auth/[...nextauth]'

export default function Test() {
  const { data: session } = useSession()
  if (typeof window === "undefined") return null

  if (session) {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <h1>Welcum</h1>

        </main>
      </>
    )
  }
}
